[package]
name = "xzma-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.38"
lzma-rs = "0.2.0"
lazy_static = "1.4.0"

[dev-dependencies]
hex = "0.4.3"
sha3 = "0.10.1"